use thiserror::Error;

/// The central error enumeration for the Chronos context engine.
///
/// **Go Parallel (Didactic):** In Go, you often use `errors.New("capture error")`
/// or wrap errors using `fmt.Errorf("database: %w", err)`. In Rust, the `thiserror`
/// crate provides a declarative macro (`#[derive(Error)]`) to automatically implement
/// the `std::error::Error` and `std::fmt::Display` traits.
/// This allows the caller to exhaustively match on specific error variants.
#[derive(Error, Debug, PartialEq, Clone)]
pub enum ChronosError {
    #[error("Capture failed: {0}")]
    Capture(String),

    #[error("Inference pipeline failed: {0}")]
    Inference(String),

    #[error("Database error: {0}")]
    Database(String),

    #[error("Configuration error: {0}")]
    Config(String),

    #[error("Operation timed out: {0}")]
    Timeout(String),

    #[error("Invalid input: {0}")]
    InvalidInput(String),
}

/// A specialized Result type mapping `std::result::Result` to `ChronosError`.
///
/// **Go Parallel:** This is akin to the standard `(T, error)` return pattern,
/// but specifically typed so consumers know they are dealing with a `ChronosError`.
pub type Result<T> = std::result::Result<T, ChronosError>;

// Note on `From<sqlx::Error>` and `From<reqwest::Error>`:
// We intentionally DO NOT implement automatic From conversions for external
// IO crates (sqlx, reqwest) inside the `chronos-core` crate.
// Adding them here would violate the Clean Boundaries rule, forcing the core
// to depend on specific implementations. Instead, the boundary crates
// (chronos-daemon, chronos-inference) will map their specific errors to these
// String-based variants (e.g., `ChronosError::Database(err.to_string())`).

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_error_formatting() {
        let err = ChronosError::Database("sqlite locked".to_string());
        let formatted = format!("{}", err);

        // Verifies that the Display implementation (generated by thiserror) matches our strings
        assert_eq!(formatted, "Database error: sqlite locked");
    }

    #[test]
    fn test_result_type_alias_success() {
        // Trivial didactic test showing instantiation
        let res: Result<i32> = Ok(42);
        assert!(res.is_ok());
    }

    #[test]
    fn test_result_type_alias_failure_pattern_match() {
        // Didactic test demonstrating Result matching via equality
        let res: Result<()> = Err(ChronosError::Timeout("VLM timeout".to_string()));

        assert_eq!(res, Err(ChronosError::Timeout("VLM timeout".to_string())));
    }
}
